import {
  Crown,
  Globe,
  Lock,
  MessageCircle,
  Rocket,
  Shield,
  Zap,
} from 'lucide-react'

import { PricingPlan } from '@/types'

export const adjectives = [
  'Happy',
  'Clever',
  'Brave',
  'Gentle',
  'Swift',
  'Bright',
  'Kind',
  'Wise',
  'Calm',
  'Bold',
  'Merry',
  'Noble',
  'Proud',
  'Quick',
  'Smart',
  'Witty',
  'Cyber',
  'Digital',
  'Quantum',
  'Neural',
  'Binary',
  'Mecha',
  'Techno',
  'Crypto',
  'Nano',
  'Proto',
  'Futuristic',
  'Mechanical',
  'Synthetic',
  'Autonomous',
  'Virtual',
  'Robotic',
  'AI',
  'Digitalized',
  'Shiny',
  'Vivid',
  'Silent',
  'Fierce',
  'Stealthy',
  'Luminous',
  'Cold',
  'Radiant',
  'Mysterious',
  'Graceful',
  'Stellar',
  'Agile',
  'Reflective',
  'Energetic',
  'Glowing',
  'Electric',
  'Cosmic',
  'Monstrous',
  'Infinite',
  'Imposing',
  'Dreamy',
  'Hyper',
  'Supreme',
  'Rogue',
  'Anomalous',
  'Evolving',
  'Unbreakable',
  'Fluid',
  'Regenerative',
  'Eccentric',
  'Disruptive',
  'Cybernetic',
  'Unseen',
  'Infinite',
  'Glimmering',
  'Divinely',
  'Time-Warped',
  'Shimmering',
  'Speedy',
  'Ultimate',
  'Calculated',
  'Powerful',
  'Legendary',
  'Divine',
  'Vengeful',
  'Mystic',
  'Beastly',
  'Fateful',
  'Ancient',
  'Ethereal',
  'Cursed',
  'Invincible',
  'Awakened',
  'Majestic',
  'Endless',
  'Immortal',
  'Cyber-Warrior',
]
export const nouns = [
  'Panda',
  'Tiger',
  'Eagle',
  'Dolphin',
  'Fox',
  'Wolf',
  'Bear',
  'Lion',
  'Hawk',
  'Owl',
  'Dragon',
  'Phoenix',
  'Falcon',
  'Lynx',
  'Leopard',
  'Jaguar',
  'Android',
  'Cyborg',
  'Matrix',
  'Vector',
  'Nexus',
  'Titan',
  'Byte',
  'Circuit',
  'Cortex',
  'Cipher',
  'Mech',
  'Bot',
  'Gizmo',
  'Drone',
  'Automaton',
  'Mechanoid',
  'Synth',
  'Robot',
  'Cybernetic',
  'NanoBot',
  'AI Unit',
  'Technoid',
  'Mech-Drone',
  'Warlock',
  'Oracle',
  'Sentinel',
  'Shifter',
  'Specter',
  'Vortex',
  'Ether',
  'Phantom',
  'Nomad',
  'Nexus-Unit',
  'Illusion',
  'Seraph',
  'Guardian',
  'Exoskeleton',
  'Glitch',
  'Valkyrie',
  'Saber',
  'Beast',
  'Kenshiro',
  'Naruto',
  'Luffy',
  'Goku',
  'Ichigo',
  'Edward',
  'Saitama',
  'Eren',
  'Deku',
  'Kamina',
  'Sakura',
  'Usagi',
  'Kaguya',
  'Makoto',
  'Shinji',
  'Lelouch',
  'Rintarou',
  'Yuji',
  'Natsu',
  'Yugi',
  'Ash',
  'Kenshiro',
  'Inuyasha',
  'Simon',
  'Kirito',
  'Gintoki',
  'Ainz',
  'Yuno',
  'Light',
  'L',
  'Vash',
  'Holo',
  'Reigen',
  'Mob',
  'Mikasa',
  'Roronoa',
  'Kamina',
  'Saber',
  'Kirei',
  'Vash',
  'Archer',
  'Yuno',
  'Akira',
  'Saitama',
  'Mob',
  'Tanjiro',
  'Nezuko',
  'Rengoku',
  'Inosuke',
  'Zenitsu',
]
export const navLinks: { href: string; label: string }[] = []

export const plans: PricingPlan[] = [
  {
    name: 'Free',
    icon: Zap,
    description: 'Perfect for getting started with secure, private chats.',
    price: '0',
    badge: null,
    features: [
      {
        icon: MessageCircle,
        title: 'Temporary Rooms',
        description: 'Create rooms that auto-delete after 24 hours',
      },
      {
        icon: Shield,
        title: 'Basic Privacy',
        description: 'End-to-end encryption for all messages',
      },
      {
        icon: Lock,
        title: 'Anonymous Access',
        description: 'Join without creating an account',
      },
    ],
  },
  {
    name: 'Pro',
    icon: Crown,
    description: 'Unlock advanced features and unlimited possibilities.',
    price: '9',
    badge: 'Most Popular',
    features: [
      {
        icon: Globe,
        title: 'Permanent Rooms',
        description: 'Create rooms that never expire',
      },
      {
        icon: Rocket,
        title: 'File Sharing',
        description: 'Share large files securely',
      },
      {
        icon: Shield,
        title: 'Advanced Admin',
        description: 'Kick/Ban users and manage permissions',
      },
    ],
  },
]
